### ISSUE TITLE
Защо има две директории? Една GameJavaFX и една Home Enternainment?

### ISSUE THREAD

**Issue by TsvetanPopharitov** [vonrepiks/TeamMaleficent#1]
Откъде да пусна това, което е направено до момента? Гърми ми като компилирам. Не трябва ли  всеки да може да го компилира това чудо? .  Някаква разговори говорихте дето да се състоят през гитхъба. Не съм запознат къде и как става това. Някаква покана или линк някой може ли да даде??

**Comment by MaximilianGeorgiev** [comment]
Просто като отваряш проекта в IDE-то отвори директно папката Home Entertainment, а не цялата папка на проекта. А относно защо има 2 директории - до колкото знам работата на няколко човека се дублираше и за това е така.

**Comment by n0Sp00n** [comment]
И аз не разбрах, защо има 2 папки. Неска почнах да работя по проекта, някой
беше сложил кода в нова папка + не бяха пренеси класове и гърмеше, после
гърмеше старт метода и се отказах накрая. Тоя тийм уорк е фейл.

2017-02-11 18:15 GMT+02:00 MaximilianGeorgiev <notifications@github.com>:

**Comment by fl3x1324** [comment]
Защото репото е направено некадърно и съдържа повече от един проект, така не се прави. Трябваше да се направи организация и да си има репота за всеки отделен проект, сега в нечий профил сте набутали всичко в едно репо... Направете организация и отделни репозиторита. Не искам да обиждам никого, просто няма никаква организация по отношение на работата по проекта, само със самоинициатива няма да стане нищо.

**Comment by Nikola-Andreev** [comment]
Хора спокойно, някой хора са вложили труд в тоя проект. Хубав или не продължаваме да го развиваме. Никой не се нае с организация и затова така се получава, но затова сме винивни всички. Нека всеки си набележи по една задача и ще довършим нещата набързо. 10 човека сме

**Comment by n0Sp00n** [comment]
Никола е прав. Без драми, ще се оправим. Тъпото е че аз работих едната
папка и като отворих другата бях като в друг свят.

**Comment by vonrepiks** [comment]
В 21 къмит, който направих беше зачистен втория проект и остана само един. Не знам дали се следят къмитите. Сега като погледнах има другия проект, че има и трето като проект, което не знам даже какво е. Относно организацията в ГитХъб за, която говори Наско незнам как се прави, така са ни учили в СофтУни да правим репозитори и така го правим, може би трябваше да я направиш преди една седмица, когато започвахме, но и сега не е късно просто дай малко разяснения. Лично с Никола, Анатоли и Иво коментирахме в чат групата във Фейсбук за проекта и това което сме качили и се разбрахме да оставим един проект и да продължим по него, Макси добави звуци, но последните два къмита са качили и стария проект. Моят номер е 0887 603 249 ако някой желае да обясня какво съм направил или желае да попита нещо по работата ми.

Последно моля Ви, както каза и Никола да пазим добрия тон и да си помагаме от това зависи крайния ни резултат, а и ще работим до май месец заедно. 

П.С. Не знам дали всички са наясно със ишутата във Гит и е хубаво да се поства във Фейсбук групата като някой качи ново ишу.

**Comment by fl3x1324** [comment]
Ок, реагирах не както трябва. Извинете ме, наистина не трябваше. Моля ви направете отганизация в GitHub. Ако искате аз може да свърша това после ще се захвана с играта, нищо не съм пипал до сега, но знам доста неща и просто не ми остана време да се включа, изобщо.

**Comment by n0Sp00n** [comment]
Евала.В наша полза е да съдействаме.

On Feb 12, 2017 12:13 AM, "Atanas Minkov" <notifications@github.com> wrote:

Ок, реагирах не както трябва. Извинете ме, наистина не трябваше. Моля ви
направете отганизация в GitHub. Ако искате аз може да свърша това после ще
се захвана с играта, нищо не съм пипал до сега, но знам доста неща и просто
не ми остана време да се включа, изобщо.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/vonrepiks/TeamMaleficent/issues/1#issuecomment-279179619>,
or mute the thread
